### ISSUE TITLE
第一条翻译有歧义

### ISSUE THREAD

**Issue by Edger** [Rikkatheworld/Effective-Kotlin-CN#1]
![image](https://user-images.githubusercontent.com/18591042/181144690-c5c4ba7c-77b5-47c1-b074-677cba4be8bd.png)

契约应该是：**依赖于抽象而不是实现**

这里看起来意思相反了

**Comment by Rikkatheworld** [comment]
这里是陈述了问题所在，不过确实产生了歧义，我修改一下， 感谢建议
